### ISSUE TITLE
wrong translation of "notebook" to other languages

### ISSUE THREAD

**Issue by bt2901** [sonic16x/interslavic#122]
![image](https://user-images.githubusercontent.com/3958256/101286438-96b9a580-37fb-11eb-812d-344a08af6bc4.png)

Английскы "notebook" означаје две вечи: компјутер и малу книгу. Автоматичны Google Translate (?) разнику не разумейе. Записник йест "maly kěšenjevy zapisnik, kniga dlja napomněnja", не "kěšenjevy kompjuter".

Як было бы правилно? Йа погледел йесм, як Википедия прекладае английски «notepad» и русскы «блокнот» (йесм погледел на имена статије и на прву одставу). Преклады од Википедийи ("интервики/interwiki") сут не автоматичны, а користитниками проверены; они болье правилны, веройетно.

Преклады, койи из Википедии возмемы:

Македонскы — Бележник, тетратка, книга/тетратка, нотес, планирач (?), агенда (?)
Српскохрватскы — Sveske, beležnice ili notesi, 
Словенскы — Poslovnik, rokovnik (?)
Сербскы — Ноутпед, свеска, белешка
Польскы — Notes, notatnik, notesik, "mały zeszyt do zapisywania uwag"
Булгарскы — тетрадка, тетрадката (?)
Украинскы — блокнот, зшиток/зошит для нотаток (?)
Hrvatsko — "nótes", "manja džepna bilježnica; podsjetnik"

**Comment by bt2901** [comment]
Other noticed mistakes:
* `at sign [@]` - uho, uško [@]   ухо, ушко [@]. Translations to other languages are corrupted in formating and content, since `@` is a special symbol
* `there will be` - bude/budut буде/будут. `No data for conjugation this verb`

**Comment by noomorph** [comment]
The translation has been fixed.
