### ISSUE TITLE
Declension offered but does not work

### ISSUE THREAD

**Issue by shibe2** [sonic16x/interslavic#127]
Declension button appears for the following word combinations:

* osnovany na
* podpirany od
* pȯlny naděje
* prěznačeny za

If you click it, the declension table shows nonsense.

**Comment by noomorph** [comment]
![image](https://user-images.githubusercontent.com/1962469/143412280-fc5c1e16-2da5-4c2f-a728-aae48e06ce23.png)

**Comment by noomorph** [comment]
Prěneseno do: https://github.com/medzuslovjansky/js-utils/issues/7
