### ISSUE TITLE
Possibly incorrect conjugation when present tense form ends with "se"

### ISSUE THREAD

**Issue by shibe2** [sonic16x/interslavic#128]
Article: **pasti sę**
Present tense: **pase**
3.sg.: **pe sę**
present_tense_stem returns "p"

**Comment by noomorph** [comment]
![image](https://user-images.githubusercontent.com/1962469/143411789-2b4bc49b-fe56-44cc-b0c9-bfec940eb96f.png)

**Comment by noomorph** [comment]
The Google Sheets DB has the irregular form, so this definitely a bug in JS logic:
![image](https://user-images.githubusercontent.com/1962469/143412168-44e4dd23-d698-491b-8b14-66aacdf6cc71.png)
