### ISSUE TITLE
About page scroll

### ISSUE THREAD

**Issue by sonic16x** [sonic16x/interslavic#13]
Move scroll on about page in desktop mode to right border
![image](https://user-images.githubusercontent.com/10794912/67267359-ca802180-f4ba-11e9-8c00-7c361d1fcd74.png)

**Comment by mudroljub** [comment]
working on chrome

![Screenshot (21)](https://github.com/sonic16x/interslavic/assets/6544761/e68224e5-0da7-468f-a7b3-fb999e117731)

**Comment by mudroljub** [comment]
working on firefox

![Screenshot (22)](https://github.com/sonic16x/interslavic/assets/6544761/ddc6c98e-e612-4ade-9bf9-6c8f283a2af0)

**Comment by noomorph** [comment]
@ru-danko so, we can close that, perhaps?
