### ISSUE TITLE
Header disappears

### ISSUE THREAD

**Issue by sonic16x** [sonic16x/interslavic#14]
Header disappears on grammar page after scroll to bottom
![image](https://user-images.githubusercontent.com/10794912/67267438-f7343900-f4ba-11e9-9385-6428642fa30b.png)

**Comment by mudroljub** [comment]
header is visible on both chrome and firefox

![Screenshot (23)](https://github.com/sonic16x/interslavic/assets/6544761/6aef8cad-15b1-4547-b48f-254400a3fa44)

**Comment by noomorph** [comment]
@ru-danko so, we can close that, perhaps? 🤔
