### ISSUE TITLE
Remove hash after return from grammar page

### ISSUE THREAD

**Issue by sonic16x** [sonic16x/interslavic#15]
Remove hash after return from grammar page
![image](https://user-images.githubusercontent.com/10794912/67267517-1df26f80-f4bb-11e9-8ed6-5ae0ff975885.png)

**Comment by jsantorek** [comment]
unable to reproduce, @sonic16x could it be already fixed?

**Comment by noomorph** [comment]
Yes, looks like an old bug. Thanks for checking, @jsantorek.

[Join our Discord](https://discord.com/invite/n3saqm27QW), just in case. We have `#razvoj-ms-slovnika` channel just in case you want to communicate about contributing to the app.
