### ISSUE TITLE
Feature request: Old Church Slavonic translations

### ISSUE THREAD

**Issue by mudroljub** [sonic16x/interslavic#154]
OCS is very important language for comparative slavistics. It is also one of the foundations for Interslavic language, also known as New Slavic/Slavonic (Новословѣнскꙑи), as oposed to Old Slavonic (Старословѣнскꙑи).
 
It would be very usefull to know language history of some Slavonic terms. Hopefully, this feature shouldn't be hard to add, because there already exist other translations. 

P.S. I have time to insert OCS translations occasionally :)

**Comment by noomorph** [comment]
@mudroljub , you can enable OCS in the settings (Additional languages).

![image](https://user-images.githubusercontent.com/1962469/139638149-55c12b67-3ea9-4fec-8f3d-41ced6c3e964.png)

To develop the translations word base, contact @ru-danko directly.
