### ISSUE TITLE
Incorrect conjugation for (certain?) "-yti" verbs with prefixes 

### ISSUE THREAD

**Issue by ProfiGMan** [sonic16x/interslavic#160]
For the verbs "ukryti" and "razmyti" the dictionary shows forms like "ukryų" and "razmyų" instead of "ukryjų" and "razmyjų", while "kryti" and "myti" are conjugated properly.

![image](https://user-images.githubusercontent.com/30975015/139637776-09103b93-d7fe-4eba-81a4-5621492bdbac.png)
![image](https://user-images.githubusercontent.com/30975015/139637840-4509a843-12ac-4e2b-aaec-8e0b081565e2.png)

**Comment by noomorph** [comment]
Fixed.
