### ISSUE TITLE
Wrong genetive form of šestsot, sedmsot, osmsot, devetsot

### ISSUE THREAD

**Issue by ProfiGMan** [sonic16x/interslavic#161]
"i" is missing in the genetive forms of "šestsot, sedmsot, osmsot, devetsot" making it the same as the nominative form. However "petsot" is declined properly.

It should be: šest**i**sot, sedm**i**sot, osm**i**sot, devet**i**sot
The forms in the dictionary: šestsot, sedmsot, osmsot, devetsot (without "i")
![вававававава](https://user-images.githubusercontent.com/30975015/140620205-5615c075-996b-45b1-86e5-b78263329ebf.png)
![аааааппппп](https://user-images.githubusercontent.com/30975015/140620226-78388ae6-3ffd-4d27-96b7-d99bfe96b352.png)

**Comment by noomorph** [comment]
Prěneseno do: https://github.com/medzuslovjansky/js-utils/issues/9
