### ISSUE TITLE
Broken indexing for "oko"

### ISSUE THREAD

**Issue by noomorph** [sonic16x/interslavic#162]
Works for "oka":

![image](https://user-images.githubusercontent.com/1962469/143411470-11c5f564-cc6d-4142-9f98-aad560697b1a.png)

Does not work for "očese":

![image](https://user-images.githubusercontent.com/1962469/143411544-589bff68-9693-4205-bb66-cdd1c7431124.png)

**Comment by mudroljub** [comment]
![Screenshot (20)](https://github.com/sonic16x/interslavic/assets/6544761/0feb0d0d-5646-4abb-b22d-a4963cd75b50)

It is working for me

**Comment by noomorph** [comment]
@mudroljub zaisto! znači, možemo zatvoriti. hvala!

**Comment by mudroljub** [comment]
nema na čemu!
