### ISSUE TITLE
[Security] Workflow ci.yml is using vulnerable action mdecoleman/pr-branch-name

### ISSUE THREAD

**Issue by Ale0x78** [sonic16x/interslavic#173]
The workflow ci.yml is referencing action mdecoleman/pr-branch-name using references 1.0.0. However this reference is missing the commit [5d3e6b404d96cac1ac4f446a1e490a6671f605df](https://github.com/mdecoleman/pr-branch-name/commits/5d3e6b404d96cac1ac4f446a1e490a6671f605df) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by noomorph** [comment]
@sonic16x
