### ISSUE TITLE
Treat various apostrophes equally

### ISSUE THREAD

**Issue by noomorph** [sonic16x/interslavic#220]
@Zmicier21 reports:

> Can we stop differentiating <code>'</code>, <code>ʼ</code> and <code>’</code> when searching?

| ![image](https://user-images.githubusercontent.com/1962469/184128859-c6699743-b799-4f8b-850a-e9bd0c1dc6a3.png) | ![image](https://user-images.githubusercontent.com/1962469/184128904-06ea127e-fada-4048-807b-e0adf3996240.png) | ![image](https://user-images.githubusercontent.com/1962469/184128885-fd74ac71-8fc6-4413-874f-e30171e6470a.png) |
|---|---|---|

**Comment by mudroljub** [comment]
How this should be treated? Should we normalize all the other apostrophes to the first one?

**Comment by noomorph** [comment]
@mudroljub yes, perhaps. Wanna try to implement?

**Comment by mudroljub** [comment]
@noomorph  ok, I will try that way

**Comment by mudroljub** [comment]
@noomorph  https://github.com/sonic16x/interslavic/pull/272
