### ISSUE TITLE
Local Environment Setup Keeps Erroring Out

### ISSUE THREAD

**Issue by nightthemoon** [sonic16x/interslavic#232]
I keep getting a ton of errors after typing "npm install"
I am running the latest npm 9.3 and just installed the latest visual studio c++
I tried running it in cmd, powershell and vs developer cmd
error log attached along with screenshots of the errors
[2022-11-22T06_01_29_988Z-debug-0.log](https://github.com/sonic16x/interslavic/files/10064404/2022-11-22T06_01_29_988Z-debug-0.log)
![image](https://user-images.githubusercontent.com/17482624/203238074-1da90981-7ec0-4d27-8b31-90b6fb7a39ca.png)
![image](https://user-images.githubusercontent.com/17482624/203238108-c84b9275-cfc4-49ec-8100-b353243ae937.png)
![image](https://user-images.githubusercontent.com/17482624/203238132-5156b7ad-9bfd-4fa8-a70c-57df6940c59f.png)
![image](https://user-images.githubusercontent.com/17482624/203238159-973b8e75-32bf-47b0-b254-e58eabc8b824.png)

**Comment by noomorph** [comment]
Try node 16.x
