### ISSUE TITLE
Sklonjenje slova "sam" jest slomjeno/zlamano

### ISSUE THREAD

**Issue by EGYTfromFDTE** [sonic16x/interslavic#246]
![зображення](https://github.com/sonic16x/interslavic/assets/113429882/f43bd686-7750-45e2-9cc1-56f156ae983d)

**Comment by noomorph** [comment]
Prividno, trěba implementovati.

**Comment by EGYTfromFDTE** [comment]
I "ono" takože
![зображення](https://github.com/sonic16x/interslavic/assets/113429882/e024d433-f07f-48e3-af0f-d8f61181b3bd)

**Comment by noomorph** [comment]
Prěneseno k: https://github.com/sonic16x/interslavic/issues/246
