### ISSUE TITLE
Word list unreadable with dark theme enabled

### ISSUE THREAD

**Issue by jsantorek** [sonic16x/interslavic#295]
![image](https://github.com/user-attachments/assets/d4717a85-6230-4cf4-bcce-cdf5dcff4db8)
browser was Opera if this helps with anything

**Comment by noomorph** [comment]
Thanks for reporting and sorry for the inconvenience.

A workaround would be to disable `Dark theme` (in Settings)

**Comment by sonic16x** [comment]
@jsantorek we fixed it now, please check it
